version: '3.9'

services:
  # backend:
  #   build: .
  #   container_name: qlttkhtcbe
  #   restart: always
  #   ports:
  #     - "${API_PORT}:${API_PORT}"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   command: npm run start:dev

  postgres:
    image: postgres:16
    container_name: qlttkhtcbe-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
